name: kru
description: Kru
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  collection: ^1.18.0
  drift: ^2.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  shadcn_ui: ^0.5.5
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.2
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.21
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  drift_dev: ^2.18.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
