name: kru
description: Kru
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  drift: ^2.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.9.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.21

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
